/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemvisprak5;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class frame1 extends javax.swing.JFrame {
    DefaultListModel<String> list1 = new DefaultListModel<>();
    String nama ;
    int pilihan;
    String barang;
    String kode ;
    int harga;
    int total_harga;
    int beli=0;
    int bayar=0;
    int kembali;

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
        tfBeli.setEditable(false);
        tfKembalian.setEditable(false);
        tfKode.setEditable(false);
        tfHarga.setEditable(false);
        btnSimpan.setText("Simpan");
        tampil_data();
    }
    
    public void reset(){
        cbBarang.setSelectedIndex(0);
        tfKode.setText(null);
        tfNama.setText(null);
        tfHarga.setText(null);
        tfTotal.setText(null);
        tfBayar.setText(null);
        tfKembalian.setText(null);
        beli=0;
        tfBeli.setText(null);
        btnSimpan.setText("Simpan");
    }
    
    public void tampil_data(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Kode Barang");
        tabel.addColumn("Harga Barang");
        tabel.addColumn("Nama Pembeli");
        tabel.addColumn("Jumlah beli"); 
        tabel.addColumn("Total Harga");
        tabel.addColumn("Total Bayar");
        tabel.addColumn("Kembalian");
        
        try{
            java.sql.Connection conn = pemvisprak5.koneksi.koneksiDB();
            String query="select* from tb_datapenjualan";
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                Object[]row ={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                tabel.addRow(row);
            }
            tbData.setModel(tabel);
            tbTotalData.setModel(tabel);
              
       
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTotalData = new javax.swing.JTable();
        btnTotalPenjualan = new javax.swing.JButton();
        tfTotalPenjualan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTotalBrgTerjual = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfBrgTerjual = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbBarang = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        tfKode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        tfKurang = new javax.swing.JButton();
        tfBeli = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfBayar = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfKembalian = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBersihkan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(224, 190, 224));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel19.setText("TOTAL DATA PENJUALAN TOKO SEMBAKO");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(192, 192, 192))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel19)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setBackground(new java.awt.Color(255, 239, 255));

        tbTotalData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Barang", "Kode Barang", "Harga", "Nama Pembeli", "Jumlah Beli", "Total Harga", "Jumlah Bayar", "Kembalian"
            }
        ));
        tbTotalData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTotalDataMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbTotalData);

        btnTotalPenjualan.setBackground(new java.awt.Color(204, 153, 255));
        btnTotalPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTotalPenjualan.setText("TOTAL PENDAPATAN");
        btnTotalPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalPenjualanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("=");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Rp");

        btnTotalBrgTerjual.setBackground(new java.awt.Color(204, 153, 255));
        btnTotalBrgTerjual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTotalBrgTerjual.setText("TOTAL BARANG TERJUAL");
        btnTotalBrgTerjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalBrgTerjualActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("=");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Karton");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(btnTotalPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfTotalPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(btnTotalBrgTerjual, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(tfBrgTerjual, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4))))
                .addGap(64, 64, 64))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(btnTotalPenjualan))
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotalBrgTerjual)
                    .addComponent(jLabel3)
                    .addComponent(tfBrgTerjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Total Data Penjualan", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(224, 190, 224));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel10.setText("DATA AKTIVITAS PENJUALAN TOKO SEMBAKO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel10)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 239, 255));

        jLabel11.setText("Nama Barang");

        cbBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Sembako --", "Minyak", "Tepung", "Gula", "Garam", "Mi Goreng", "Mi Kuah", "Kopi", " " }));
        cbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBarangActionPerformed(evt);
            }
        });

        jLabel12.setText("Kode Barang");

        jLabel13.setText("Harga");

        jLabel14.setText("Nama Pembeli");

        jLabel15.setText("Jumlah Beli / karton");

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnTambah.setText("+");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tfKurang.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tfKurang.setText("-");
        tfKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKurangActionPerformed(evt);
            }
        });

        tfBeli.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel16.setText("Total Harga");

        jLabel17.setText("Jumlah Bayar");

        tfBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBayarActionPerformed(evt);
            }
        });

        jLabel18.setText("Kembalian");

        btnBayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBayar.setText("BAYAR");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBersihkan.setBackground(new java.awt.Color(255, 153, 153));
        btnBersihkan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBersihkan.setText("BERSIHKAN SEMUA DATA");
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Barang", "Kode Barang", "Harga", "Nama Pembeli", "Jumlah Beli", "Total Harga", "Jumlah Bayar", "Kembalian"
            }
        ));
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbData);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfKode, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(47, 47, 47)
                                        .addComponent(cbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(tfKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfBayar)
                                            .addComponent(tfKembalian)
                                            .addComponent(btnBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(jLabel16)
                                        .addGap(39, 39, 39)
                                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(64, 64, 64))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17)
                    .addComponent(tfBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btnBayar))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(btnTambah)
                            .addComponent(tfBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSimpan)
                            .addComponent(btnReset)
                            .addComponent(tfKurang)))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBersihkan)
                    .addComponent(btnHapus))
                .addGap(138, 138, 138))
        );

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Aktivitas Penjualan", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBarangActionPerformed
        // TODO add your handling code here:
        pilihan = cbBarang.getSelectedIndex();
        if(pilihan==0){
            reset();
        }

        if(pilihan==1){
            kode = "001";
            harga = 200000;
            barang = "Minyak";
        }
        if(pilihan==2){
            kode = "002";
            harga = 150000;
            barang = "Tepung";
        }
        if(pilihan==3){
            kode = "003";
            harga = 100000;
            barang = "Gula";
        }
        if(pilihan==4){
            kode = "004";
            harga = 50000;
            barang = "Garam";
        }
        if(pilihan==5){
            kode = "005";
            harga = 170000;
            barang = "Mi Goreng";
        }
        if(pilihan==6){
            kode = "006";
            harga = 165000;
            barang = "Mi Kuah";
        }
        if(pilihan==7){
            kode = "007";
            harga = 80000;
            barang = "Kopi";
        }
        tfKode.setText(kode);
        tfHarga.setText(""+harga);
    }//GEN-LAST:event_cbBarangActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        beli++;
        tfBeli.setText(Integer.toString(beli));
        total_harga = beli*harga;
        tfTotal.setText(""+total_harga);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tfKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKurangActionPerformed
        // TODO add your handling code here:
        beli--;
        tfBeli.setText(Integer.toString(beli));
          if (beli<0){
          tfBeli.setText("0");
          beli=0;
        }
        tfBeli.setText(Integer.toString(beli));
        total_harga = beli*harga;
        tfTotal.setText(""+total_harga);
    }//GEN-LAST:event_tfKurangActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        nama=tfNama.getText();
        String totalBayarText = tfBayar.getText().trim(); // Dapatkan teks dan hapus spasi
        if (totalBayarText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan pembayaran dengan benar. Harap isi total bayar.");
        }else{
            bayar = Integer.parseInt(totalBayarText);
            if(bayar==0||bayar<total_harga){
            JOptionPane.showMessageDialog(null, "Pembayaran anda kurang, Tolong Masukan Pembayaran dengan sesuai!!");
            }else{
                kembali = bayar-total_harga;
                tfKembalian.setText(""+kembali);
            }                                      
        }
    }//GEN-LAST:event_btnBayarActionPerformed

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
        nama = tfNama.getText();
    }//GEN-LAST:event_tfNamaActionPerformed

    private void tfBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBayarActionPerformed
        // TODO add your handling code here:
        bayar = Integer.parseInt(tfBayar.getText());
    }//GEN-LAST:event_tfBayarActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (btnSimpan.getText().equals("Simpan")) {
            if (barang==null||kode==null||harga==0||beli==0||total_harga==0||bayar==0) {
                JOptionPane.showMessageDialog(null, "Tolong Input Data dengan Benar");
                  reset();
            }else{
                try{
                    String sql="insert into tb_datapenjualan values('"+barang+"','"+kode+"','"+harga+"','"+tfNama.getText()+"','"+beli+"','"+total_harga+"','"+bayar+"','"+kembali+  "')";
                    java.sql.Connection conn=(java.sql.Connection)pemvisprak5.koneksi.koneksiDB();
                    java.sql.PreparedStatement 
                    pst=conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil disimpan");
                    reset();
                    tampil_data();
                    list1.addElement(nama + " telah Membeli Barang Dengan Kode " + kode);
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Gagal disimpan");
                    System.out.println(e.getMessage());
                }
            }
        }else if (btnSimpan.getText().equals("Edit")){
            try{
                String update ="UPDATE tb_datapenjualan SET harga_barang='"+harga+"',kode_barang='"+kode+"',nama_barang='"+barang+"',jumlah_beli='"+beli+"',total_harga='"+total_harga+"',total_bayar='"+bayar+"',kembalian='"+kembali+"' where nama_pembeli='"+tfNama.getText()+"'";
                java.sql.Connection conn=(java.sql.Connection)pemvisprak5.koneksi.koneksiDB();
                java.sql.PreparedStatement 
                pst=conn.prepareStatement(update);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Edit Berhasil disimpan");
                reset();
                tampil_data();
                 list1.addElement( "Data pembelian dengan kode " + kode + " telah DiEdit");
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Gagal disimpan");
                System.out.println(e.getMessage());
            }
        }
        list1.addElement(nama + " telah Membeli Barang Dengan Kode " + kode);
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        if(tfKode.getText().equals("")&&tfNama.getText().equals("")&&tfTotal.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Form Input Sudah bersih"); 
        }else {
            reset();
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
        // TODO add your handling code here:
        int baris = tbData.rowAtPoint(evt.getPoint());
       
        String a = tbData.getValueAt(baris, 0).toString();
        cbBarang.setSelectedItem(a);
        String b = tbData.getValueAt(baris, 1).toString();
        tfKode.setText(b);
        String c = tbData.getValueAt(baris, 2).toString();
        tfHarga.setText(c);
        String d = tbData.getValueAt(baris, 3).toString();
        tfNama.setText(d);
        String e = tbData.getValueAt(baris, 4).toString();
        tfBeli.setText(e);
        String f = tbData.getValueAt(baris, 5).toString();
        tfTotal.setText(f);
        String g = tbData.getValueAt(baris, 6).toString();
        tfBayar.setText(g);
        String h = tbData.getValueAt(baris, 7).toString();
        tfKembalian.setText(h);
        btnSimpan.setText("Edit");
    }//GEN-LAST:event_tbDataMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(tbData==null){
            JOptionPane.showMessageDialog(null, "Data Telah kosong!");
        }else if(tfKode.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan dihapus!");
        }else{
            int jawab = JOptionPane.showConfirmDialog(null,"Apakah Yakin Data akan dihapus?","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(jawab==0){
                try{
                    String sql="delete from tb_datapenjualan where kode_barang ='"+kode+"'";
                    java.sql.Connection conn=(java.sql.Connection)pemvisprak5.koneksi.koneksiDB();
                    java.sql.PreparedStatement 
                    pst=conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil dihapus");
                    tampil_data();
                    reset();
                    list1.addElement( "Data pembelian dengan kode " + kode + " telah Dihapus ");
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Gagal disimpan");
                    System.out.println(e.getMessage());
                } 
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        // TODO add your handling code here:
        if(tbData==null){
            JOptionPane.showMessageDialog(null, "Data Telah kosong!");
        }else{
            int jawab = JOptionPane.showConfirmDialog(null,"Apakah Yakin Data akan direset?","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(jawab==0){
                try{
                    String sql="delete from tb_datapenjualan ";
                    java.sql.Connection conn=(java.sql.Connection)pemvisprak5.koneksi.koneksiDB();
                    java.sql.PreparedStatement 
                    pst=conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil disimpan");
                    reset();
                    tampil_data();
                    list1.addElement( "Semua data Telah Di reset ulang (Kosong)");
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Gagal disimpan");
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnBersihkanActionPerformed

    private void tbTotalDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTotalDataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbTotalDataMouseClicked

    private void btnTotalPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalPenjualanActionPerformed
        // TODO add your handling code here:
        int totalPenjualan = 0;
        
        for (int i = 0; i < tbData.getRowCount(); i++) {
            int totalHarga = Integer.parseInt(tbData.getValueAt(i, 5).toString());
            totalPenjualan += totalHarga;
        }
        tfTotalPenjualan.setText(String.valueOf(totalPenjualan));
    }//GEN-LAST:event_btnTotalPenjualanActionPerformed

    private void btnTotalBrgTerjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalBrgTerjualActionPerformed
        // TODO add your handling code here:
        int totalTerjual = 0;
        
        for (int i = 0; i < tbData.getRowCount(); i++) {
            int totalBarang = Integer.parseInt(tbData.getValueAt(i, 4).toString());
            totalTerjual += totalBarang;
        }
        tfBrgTerjual.setText(String.valueOf(totalTerjual));
    }//GEN-LAST:event_btnTotalBrgTerjualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTotalBrgTerjual;
    private javax.swing.JButton btnTotalPenjualan;
    private javax.swing.JComboBox<String> cbBarang;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbData;
    private javax.swing.JTable tbTotalData;
    private javax.swing.JTextField tfBayar;
    private javax.swing.JTextField tfBeli;
    private javax.swing.JTextField tfBrgTerjual;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfKembalian;
    private javax.swing.JTextField tfKode;
    private javax.swing.JButton tfKurang;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfTotalPenjualan;
    // End of variables declaration//GEN-END:variables
}
